<?php

/**
 * @file
 * Farm REI module.
 */

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 */
function farm_rei_log_presave($entity) {

  // If the log is not an input log, bail.
  if ($entity->type != 'farm_input') {
    return;
  }

  // Get an entity metadata wrapper for the log.
  $log_wrapper = entity_metadata_wrapper('log', $entity);

  // If an REI is already set don't change it.
  $rei = $log_wrapper->field_farm_rei->value();
  // Check the field value using isset() so that a value of 0 can override
  // a materials REI value on the input log.
  if (isset($rei)) {
    return;
  }

  // If there is no farm material reference with the log, bail.
  if (empty($log_wrapper->field_farm_material->value())) {
    return;
  }

  // Save the longest REI defined by materials the log references.
  $max_rei = 0;
  foreach ($log_wrapper->field_farm_material as $material) {

    // If the material doesn't have an REI defined, skip it.
    if (!$material->field_farm_rei->value()) {
      continue;
    }

    // Save the longest material REI.
    $rei_value = $material->field_farm_rei->value();
    if ($rei_value > $max_rei) {
      $max_rei = $rei_value;
    }
  }

  // Update the log's REI to the largest REI provided by materials.
  if (!empty($max_rei)) {
    $log_wrapper->field_farm_rei->set($max_rei);
  }
}

/**
 * Implements hook_entity_view_alter().
 */
function farm_rei_entity_view_alter(&$build, $type) {

  // Start a list of logs to check.
  $logs = array();

  // Start a list of area IDs to check.
  $area_tids = array();

  // If viewing an asset, display a message if its current location has
  // an active REI.
  if ($type == 'farm_asset' && !empty($build['#entity'])) {

    // Alias the asset.
    $asset = $build['#entity'];

    // Save the assets current location.
    $areas = farm_movement_asset_location($asset);

    // Save the area tids to check later.
    foreach ($areas as $area) {
      $area_tids[] = $area->tid;
    }
  }

  // If viewing a taxonomy term that is an area, display a warning message if
  // an input log defines an active REI.
  if ($type == 'taxonomy_term' && !empty($build['#term'])) {

    // Alias the term and tid.
    $term = $build['#term'];

    // If the term is not in the farm_areas vocabulary, bail.
    if ($term->vocabulary_machine_name != 'farm_areas') {
      return;
    }

    // Save the area tid to check later.
    $area_tids = array($term->tid);
  }

  // Get all input logs that reference saved areas.
  if (!empty($area_tids)) {

    // Include child & parent areas.
    foreach ($area_tids as $tid) {

      // Load child areas.
      $child_areas = taxonomy_get_children($tid);

      // Load parent areas.
      $parent_areas = taxonomy_get_parents($tid);

      // Include all child & parent area tids.
      foreach (array_merge($parent_areas, $child_areas) as $area) {
        $area_tids[] = $area->tid;
      }
    }

    // Start a query for input logs.
    $query = farm_log_query(REQUEST_TIME, TRUE, 'farm_input', FALSE);

    // Add the log ID field.
    $query->addField('ss_log', 'id');

    // Add tag to identify where this came from.
    $query->addTag('farm_rei_entity_view_alter');

    // Join in the area field. Use an inner join to exclude logs that do not
    // have an area reference.
    $query->innerJoin('field_data_field_farm_area', 'ss_fdffa', "ss_fdffa.entity_type = 'log' AND ss_fdffa.entity_id = ss_log.id AND ss_fdffa.deleted = 0");

    // Only include logs that reference the area.
    $query->where('ss_fdffa.field_farm_area_tid IN (:tids)', array(':tids' => $area_tids));

    // Execute query.
    $result = $query->execute();

    // Get log IDs.
    $log_ids = $result->fetchCol();

    // Load logs if any are found.
    if (!empty($log_ids)) {
      $logs = log_load_multiple($log_ids);
    }
  }

  // Check all logs for an active REI.
  foreach ($logs as $log) {

    // Check if the log sets an REI.
    $rei_expiration = farm_rei_log_rei_expiration($log);

    // If the log doesn't set an REI, or it has expired, skip it.
    if (empty($rei_expiration) || $rei_expiration < REQUEST_TIME) {
      continue;
    }

    // Format REI expiration timestamp.
    $rei_expiration_string = strftime('%b %d, %Y at %r', $rei_expiration);

    // Get the log URL and name.
    $log_uri = entity_uri('log', $log);
    $log_path = $log_uri['path'];
    $log_name = entity_label('log', $log);

    // Display a warning message referencing the input log.
    $args = array(
      '@rei_expiration' => $rei_expiration_string,
      '!log_path' => url($log_path),
      '%log_name' => $log_name,
    );
    $message = t('This area has restricted-entry until @rei_expiration. See <a href="!log_path">%log_name</a> for details.', $args);
    drupal_set_message($message, 'warning');
  }

  // If the type is not a log, bail.
  if ($type != 'log' || empty($build['#entity'])) {
    return;
  }

  // Alias the log entity.
  $log = $build['#entity'];

  // Get the logs REI expiration timestamp or NULL.
  $rei_expiration = farm_rei_log_rei_expiration($log);

  // If the log doesn't have an REI, bail.
  if (empty($rei_expiration)) {
    return;
  }

  // If the REI has already expired, bail.
  if ($rei_expiration < REQUEST_TIME) {
    return;
  }

  // Get an entity metadata wrapper for the log.
  $log_wrapper = entity_metadata_wrapper('log', $log);

  // Start building a message to display.
  $message = t('This log defines an active restricted entry');

  // Build area names.
  $count_areas = count($log_wrapper->field_farm_area);
  if ($count_areas > 0) {

    // Include first area name.
    $area_names = $log_wrapper->field_farm_area[0]->name->value();

    // Append (+ # more) if there are multiple areas.
    if ($count_areas > 1) {
      $area_names .= ' (+ ' . ($count_areas - 1) . ' ' . t('more') . ')';
    }

    // Add area names to message.
    $message .= ' ' . t('in') . ' ' . $area_names;
  }

  // Format the rei expiration timestamp.
  $rei_expiration_string = strftime('%b %d, %Y at %r', $rei_expiration);

  // Add expiration to message.
  $message .= ' ' . t('until @rei_expiration', array('@rei_expiration' => $rei_expiration_string));

  // Set warning message.
  drupal_set_message($message, 'warning');
}

/**
 * Helper function that returns an REI expiration timestamp.
 *
 * @param Log $log
 *   The input log to load REI expiration from.
 *
 * @return int|null
 *   The REI expiration timestamp or NULL if no REI is set.
 */
function farm_rei_log_rei_expiration($log) {

  // If not an input log, bail.
  if ($log->type != 'farm_input') {
    return NULL;
  }

  // If the log is not done, bail.
  if (!$log->done) {
    return NULL;
  }

  // Get an entity metadata wrapper.
  $log_wrapper = entity_metadata_wrapper('log', $log);

  // If no REI is set, bail.
  if (empty($log_wrapper->field_farm_rei)) {
    return NULL;
  }

  // Get the REI days.
  $rei_days = $log_wrapper->field_farm_rei->value();

  // Build expiration timestamp.
  $rei_expiration = strtotime('+ ' . $rei_days . ' days', $log->timestamp);

  return $rei_expiration;
}
